sudo: false
language: go
git:
    depth: 1
install: 
    - wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.tar.gz
    - tar xvfz hugo.tar.gz
    - rm -fr public
script:
    - ./hugo version
    - ./hugo --cleanDestinationDir --forceSyncStatic --gc --ignoreCache --minify
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: istek/istek.github.io
    fqdn: www.istek.cc
    target_branch: master
    email: krazelcn@gmail.com
    name: istek